name: Build Alist

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Check Alist directory
      run: |
        if [ ! -d "Alist" ]; then echo "Alist directory not found"; exit 1; fi

    - name: Run Buildx
      run: |
        cd Alist
        docker buildx build . \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          --output "type=image,push=true" \
          --file Dockerfile-hub \
          --tag skylerhe/alist:${{ github.event.inputs.tag }} \
          --tag skylerhe/alist:latest
